name: infoboektest
main: me.jensie1996.InfoBoek.InfoBoekClass
author: Jensie1996
website: http://www.thebelgiumgames.be
version: 1.0
commands:
    ibreload:
        description: Reload de config.
        usage: /<command>
    ibgetbook:
        description: Verkrijgen van het boek zonder te hoeven aanmelden.
        usage: /<command>
        permissions: ibgetbook