name: infoboektest
main: me.jensie1996.infoBoek.InfoBoekClass
version: 1.0
commands:
    ibreload:
        description: Herladen van de config.
        usage: /<command>
    ibgetbook:
        description: Verkrijgen van het boek zonder te hoeven aanmelden.
        usage: /<command>
        permissions: ibgetbook